routes/web.php
<?php

//Route::get('/', 'HomeController@index');

Route::redirect('/', 'login');

Auth::routes();

Route::get('auth/user/switch', 'UsersController@switchBack')->name('switch.back');

Route::group(['prefix' => 'requester'], function () {
    Route::get('tickets/view/{token}', 'Requester\RequesterTicketsController@show')->name('requester.tickets.show');
    Route::post('tickets/{token}/comments', 'Requester\RequesterCommentsController@store')->name('requester.comments.store');
    Route::get('tickets/{token}/rate', 'Requester\RequesterTicketsController@rate')->name('requester.tickets.rate');
    Route::get('tickets/create', 'Requester\RequesterTicketsController@create')->name('requester.tickets.create');
    Route::post('tickets/save', 'Requester\RequesterTicketsController@save')->name('requester.tickets.store');
});

Route::post('webhook/bitbucket', 'WebhookController@store');

Route::group(['middleware' => ['auth', 'userLocale']], function () {
    Route::get('actions/resolve/{ticket}', 'Actions\ActionsController@resolve')->name('ac.resolve');
    Route::post('actions/store', 'Actions\ActionsController@save')->name('ac.resolve.store');

    Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::post('password', 'ProfileController@password')->name('profile.password');
    Route::post('photo', 'ProfileController@photo')->name('profile.photo');

    Route::get('tickets/merge', 'Tickets\TicketsMergeController@index')->name('tickets.merge.index');
    //Route::post('tickets/merge', 'Tickets\TicketsMergeController@store')->name('tickets.merge.store');
    Route::get('tickets/search/{text}', 'Tickets\TicketsSearchController@index')->name('tickets.search');
    Route::resource('tickets', 'Tickets\TicketsController', ['except' => ['edit', 'destroy']]);
    Route::post('tickets/{ticket}/assign', 'Tickets\TicketsAssignController@store')->name('tickets.assign');
    Route::post('tickets/{ticket}/comments', 'CommentsController@store')->name('comments.store');
    Route::resource('tickets/{ticket}/tags', 'Tickets\TicketsTagsController', ['only' => ['store', 'destroy'], 'as' => 'tickets']);
    Route::post('tickets/{ticket}/reopen', 'Tickets\TicketsController@reopen')->name('tickets.reopen');

    Route::post('tickets/{ticket}/escalate', 'Tickets\TicketsEscalateController@store')->name('tickets.escalate.store');
    Route::delete('tickets/{ticket}/escalate', 'Tickets\TicketsEscalateController@destroy')->name('tickets.escalate.destroy');

    Route::post('tickets/{ticket}/issue', 'Tickets\TicketsIssueController@store')->name('tickets.issue.store');
    Route::post('tickets/{ticket}/idea', 'Tickets\TicketsIdeaController@store')->name('tickets.idea.store');

//    Route::resource('leads', 'Leads\LeadsController');
//    Route::get('leads/search/{text}', 'Leads\LeadsSearchController@index')->name('leads.search');
//    Route::post('leads/{lead}/assign', 'Leads\LeadAssignController@store')->name('leads.assign');
//    Route::post('leads/{lead}/status', 'Leads\LeadStatusController@store')->name('leads.status.store');
//    Route::resource('leads/{lead}/tags', 'Leads\LeadTagsController', ['only' => ['store', 'destroy'], 'as' => 'leads']);
//    Route::resource('leads/{lead}/tasks', 'Leads\LeadTasksController', ['only' => ['index', 'store', 'update', 'destroy'], 'as' => 'leads']);

    Route::resource('tasks', 'TasksController', ['only' => ['index', 'update', 'destroy']]);

    Route::resource('teams', 'TeamsController');
    Route::get('teams/{team}/agents', 'TeamAgentsController@index')->name('teams.agents');
    Route::get('teams/{token}/join', 'TeamMembershipController@index')->name('membership.index');
    Route::post('teams/{token}/join', 'TeamMembershipController@store')->name('membership.store');

    Route::get('dashboard', 'Reports\DashboardController@index')->name('dash.index');
    Route::get('slareport', 'Reports\SLAReportController@index')->name('sla.report');

    Route::group(['middleware' => 'can:see-admin'], function () {
        Route::resource('ideas', 'IdeasController');
        Route::get('roadmap', 'RoadmapController@index')->name('roadmap.index');
        Route::resource('ideas/{idea}/tags', 'IdeaTagsController', ['only' => ['store', 'destroy'], 'as' => 'ideas']);
        Route::post('ideas/{idea}/issue', 'IdeaIssueController@store')->name('ideas.issue.store');

        Route::resource('users', 'UsersController');
        Route::post('users/resend', 'UsersController@sendResetLinkEmail')->name('users.password.reset');
        Route::get('users/{user}/impersonate', 'UsersController@impersonate')->name('users.impersonate');
        Route::resource('settings', 'SettingsController', ['only' => ['edit', 'update']]);

        Route::resource('questions', 'Help\HelpQuestionsController', ['as' => 'qs']);
        Route::resource('help', 'Help\HelpAnswersController', ['as' => 'hp']);
        Route::resource('actions', 'MasterData\SupportedActionsController', ['as' => 'ac']);
        Route::resource('cause', 'MasterData\RootCauseController', ['as' => 'rc']);
        Route::resource('company', 'Supported\CompanyController', ['as' => 'co']);
        Route::resource('customer', 'Supported\CustomerController', ['as' => 'cu']);
        Route::resource('solution', 'Supported\SolutionController', ['as' => 'so']);
        Route::resource('sla', 'Reports\SLAController', ['only' => ['index', 'store', 'update']]);
    });

    Route::get('reports', 'ReportsController@index')->name('reports.index');

    Route::group(['prefix' => 'incidents'], function () {
        Route::get('all', 'IncidentsController@index')->name('incidents.index');
    });
});

app/Http/Controllers/Reports/DashboardController.php
<?php

namespace App\Http\Controllers\Reports;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Company;

class DashboardController extends Controller
{
    public function index() {
        $companies = Company::all();
        return view('reports.dashboard.index',compact('companies'));
    }
}

app/Http/Controllers/Reports/SLAController.php
<?php

namespace App\Http\Controllers\Reports;

use App\SLAConfiguration;
use App\Http\Controllers\Controller;

class SLAController extends Controller
{
    public function index() {
        $configurations = SLAConfiguration::all();
        return view('reports.sla.index', compact('configurations'));
    }

    public function store() {
        $valid = $this->validate(request(), [
            'unit' => 'required',
            'measure' => 'required'
        ]);

        foreach ($valid['unit'] as $key => $value) {
            $config = SLAConfiguration::find($key);
            $config->unit = $value;
            $config->measure = $valid['measure'][$key];
            $config->save();
        }

        return redirect()->route('sla.index')->with(['success'=>'SLA updated successfully']);
    }
}

app/Http/Controllers/Reports/SLAReportController.php
<?php

namespace App\Http\Controllers\Reports;

use App\SLAConfiguration;
use App\TicketReport;
use App\Ticket;
use App\Http\Controllers\Controller;

class SLAReportController extends Controller
{
    public function index() {
        $user = auth()->user();

        $reports = TicketReport::where('user_id',$user->id)->get();

        $ids = $reports->pluck('ticket_id');
        $tickets = Ticket::where('user_id', $user->id)->whereNotIn('id', $ids)->get();

        return view('reports.sla.report', ['tickets' => $tickets, 'reports' => $reports ]);
    }
}

app/Http/Controllers/ReportsController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Repositories\KpiRepository;

class ReportsController extends Controller
{
    public function index(KpiRepository $repository)
    {
        $startDate = request('startDate') ?: Carbon::now()->startOfMonth();
        $endDate   = request('endDate') ?: Carbon::now()->endOfMonth();

        return view('reports.index', ['repository' => $repository->forDates($startDate, $endDate)]);
    }
}

resources/views/reports/sla/index.blade.php
@extends('layouts.app')
@section('content')
    <h3 class="page-title">Configure SLA's</h3>

    {{ Form::open(["url" => route("sla.store")]) }}
    <table class="table table-hover table-striped table-condensed table-bordered">
        <thead>
        <th>Priority</th>
        <th>Unit</th>
        <th>Measure</th>
        <th>From event</th>
        <th>To event</th>
        </thead>
        <tbody>
        @forelse($configurations as $config)
            <tr>
                <td>{{ __('ticket.' . \App\Ticket::priorityNameFor($config->priority)) }}</td>
                <td class="unit-input">
                    <input type="text" name="unit[{{$config->id}}]" value="{{ $config->unit }}" class="form-control"/>
                </td>
                <td>
                    {{ Form::select('measure['.$config->id.']', \App\SLAConfiguration::measures(), $config->measure , ['class'=>'form-control']) }}
                </td>
                <td>{{ __('ticket.' . \App\Ticket::statusNameFor($config->start_event)) }}</td>
                <td>{{ __('ticket.' . \App\Ticket::statusNameFor($config->end_event)) }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="5" class="text-center">No SLA configurations available, please update master data</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    <button class="btn btn-primary" type="submit">@icon(save) Update Configuration</button>
    {{ Form::close() }}
@endsection

resources/views/reports/sla/report.blade.php
@extends('layouts.app')
@section('content')
    <h3 class="page-title">SLA Report for {{ Auth::user()->name }}</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Answered Tickets</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-condensed table-bordered">
                <tr>
                    <th>Ticket</th>
                    <th>User</th>
                    <th>Event</th>
                    <th>Time taken</th>
                    <th>SLA</th>
                    <th>Difference</th>
                    <th>Rating</th>
                </tr>
                @forelse($reports as $report)
                    <tr>
                        <td>{{$report->ticket->title}}</td>
                        <td>{{$report->user->name}}</td>
                        <td>{{$report->startEvent()}} <span
                                    style="padding: 0 12px; display: inline-block">-></span> {{$report->endEvent()}}
                        </td>
                        @foreach($report->slaRating() as $report)
                            <td>{!! $report !!}</td>
                        @endforeach
                    </tr>
                @empty
                    <tr>
                        <td class="text-center" colspan="7">No Tickets Answered</td>
                    </tr>
                @endforelse
            </table>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Unanswered Tickets</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-condensed table-bordered">
                <tr>
                    <th>Status/Priority</th>
                    <th>Ticket</th>
                    <th>Unanswered since</th>
                </tr>
            @forelse($tickets as $ticket)
                <tr>
                    <td>@include('components.ticket.status',$ticket)</td>
                    <td><a href="{{route('tickets.show',$ticket->id)}}">#{{$ticket->id}} · {{$ticket->title}}</a></td>
                    <td>{{$ticket->created_at->diffForHumans()}}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="3" class="text-center">Assigned tickets answered</td>
                </tr>
            @endforelse
            </table>
        </div>
    </div>


@endsection