routes/web.php
<?php

//Route::get('/', 'HomeController@index');

Route::redirect('/', 'login');

Auth::routes();

Route::get('auth/user/switch', 'UsersController@switchBack')->name('switch.back');

Route::group(['prefix' => 'requester'], function () {
    Route::get('tickets/view/{token}', 'Requester\RequesterTicketsController@show')->name('requester.tickets.show');
    Route::post('tickets/{token}/comments', 'Requester\RequesterCommentsController@store')->name('requester.comments.store');
    Route::get('tickets/{token}/rate', 'Requester\RequesterTicketsController@rate')->name('requester.tickets.rate');
    Route::get('tickets/create', 'Requester\RequesterTicketsController@create')->name('requester.tickets.create');
    Route::post('tickets/save', 'Requester\RequesterTicketsController@save')->name('requester.tickets.store');
});

Route::post('webhook/bitbucket', 'WebhookController@store');

Route::group(['middleware' => ['auth', 'userLocale']], function () {
    Route::get('actions/resolve/{ticket}', 'Actions\ActionsController@resolve')->name('ac.resolve');
    Route::post('actions/store', 'Actions\ActionsController@save')->name('ac.resolve.store');

    Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::post('password', 'ProfileController@password')->name('profile.password');
    Route::post('photo', 'ProfileController@photo')->name('profile.photo');

    Route::get('tickets/merge', 'Tickets\TicketsMergeController@index')->name('tickets.merge.index');
    //Route::post('tickets/merge', 'Tickets\TicketsMergeController@store')->name('tickets.merge.store');
    Route::get('tickets/search/{text}', 'Tickets\TicketsSearchController@index')->name('tickets.search');
    Route::resource('tickets', 'Tickets\TicketsController', ['except' => ['edit', 'destroy']]);
    Route::post('tickets/{ticket}/assign', 'Tickets\TicketsAssignController@store')->name('tickets.assign');
    Route::post('tickets/{ticket}/comments', 'CommentsController@store')->name('comments.store');
    Route::resource('tickets/{ticket}/tags', 'Tickets\TicketsTagsController', ['only' => ['store', 'destroy'], 'as' => 'tickets']);
    Route::post('tickets/{ticket}/reopen', 'Tickets\TicketsController@reopen')->name('tickets.reopen');

    Route::post('tickets/{ticket}/escalate', 'Tickets\TicketsEscalateController@store')->name('tickets.escalate.store');
    Route::delete('tickets/{ticket}/escalate', 'Tickets\TicketsEscalateController@destroy')->name('tickets.escalate.destroy');

    Route::post('tickets/{ticket}/issue', 'Tickets\TicketsIssueController@store')->name('tickets.issue.store');
    Route::post('tickets/{ticket}/idea', 'Tickets\TicketsIdeaController@store')->name('tickets.idea.store');

//    Route::resource('leads', 'Leads\LeadsController');
//    Route::get('leads/search/{text}', 'Leads\LeadsSearchController@index')->name('leads.search');
//    Route::post('leads/{lead}/assign', 'Leads\LeadAssignController@store')->name('leads.assign');
//    Route::post('leads/{lead}/status', 'Leads\LeadStatusController@store')->name('leads.status.store');
//    Route::resource('leads/{lead}/tags', 'Leads\LeadTagsController', ['only' => ['store', 'destroy'], 'as' => 'leads']);
//    Route::resource('leads/{lead}/tasks', 'Leads\LeadTasksController', ['only' => ['index', 'store', 'update', 'destroy'], 'as' => 'leads']);

    Route::resource('tasks', 'TasksController', ['only' => ['index', 'update', 'destroy']]);

    Route::resource('teams', 'TeamsController');
    Route::get('teams/{team}/agents', 'TeamAgentsController@index')->name('teams.agents');
    Route::get('teams/{token}/join', 'TeamMembershipController@index')->name('membership.index');
    Route::post('teams/{token}/join', 'TeamMembershipController@store')->name('membership.store');

    Route::get('dashboard', 'Reports\DashboardController@index')->name('dash.index');
    Route::get('slareport', 'Reports\SLAReportController@index')->name('sla.report');

    Route::group(['middleware' => 'can:see-admin'], function () {
        Route::resource('ideas', 'IdeasController');
        Route::get('roadmap', 'RoadmapController@index')->name('roadmap.index');
        Route::resource('ideas/{idea}/tags', 'IdeaTagsController', ['only' => ['store', 'destroy'], 'as' => 'ideas']);
        Route::post('ideas/{idea}/issue', 'IdeaIssueController@store')->name('ideas.issue.store');

        Route::resource('users', 'UsersController');
        Route::post('users/resend', 'UsersController@sendResetLinkEmail')->name('users.password.reset');
        Route::get('users/{user}/impersonate', 'UsersController@impersonate')->name('users.impersonate');
        Route::resource('settings', 'SettingsController', ['only' => ['edit', 'update']]);

        Route::resource('questions', 'Help\HelpQuestionsController', ['as' => 'qs']);
        Route::resource('help', 'Help\HelpAnswersController', ['as' => 'hp']);
        Route::resource('actions', 'MasterData\SupportedActionsController', ['as' => 'ac']);
        Route::resource('cause', 'MasterData\RootCauseController', ['as' => 'rc']);
        Route::resource('company', 'Supported\CompanyController', ['as' => 'co']);
        Route::resource('customer', 'Supported\CustomerController', ['as' => 'cu']);
        Route::resource('solution', 'Supported\SolutionController', ['as' => 'so']);
        Route::resource('sla', 'Reports\SLAController', ['only' => ['index', 'store', 'update']]);
    });

    Route::get('reports', 'ReportsController@index')->name('reports.index');

    Route::group(['prefix' => 'incidents'], function () {
        Route::get('all', 'IncidentsController@index')->name('incidents.index');
    });
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends BaseModel
{
    protected $table = 'supported_company';
}

app/SupportedAction.php
<?php

namespace App;

class SupportedAction extends BaseModel
{
    //
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CompanyController extends Controller
{
    //
}

app/Http/Controllers/Supported/CompanyController.php
<?php

namespace App\Http\Controllers\Supported;

use App\Company;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CompanyController extends Controller
{
    public function index() {
        $companies = Company::paginate(25);
        return view('supported.company.index', compact('companies'));
    }

    public function create()
    {
        return view('supported.company.create');
    }

    public function edit(Company $company)
    {
        return view('supported.company.edit', ['company' => $company]);
    }

    public function update(Company $company)
    {
        $newAction = $this->validate(request(), [
            'name' => 'required|min:3',
            'address' => 'required|min:3',
            'phone' => 'required|min:3',
            'contact_number' => 'required|min:10',
            'email' => 'required|email',
            'support_email' => 'required|email',
            'web' => 'required|min:3'
        ]);

        $company->update($newAction);

        return redirect()->route('co.company.index');
    }

    public function store()
    {
        $action = $this->validate(request(), [
            'name' => 'required|min:3',
            'address' => 'required|min:3',
            'phone' => 'required|min:3',
            'contact_number' => 'required|min:10',
            'email' => 'required|email',
            'support_email' => 'required|email',
            'web' => 'required|min:3'
        ]);

        Company::create($action);

        return redirect()->route('co.company.index');
    }

    public function destroy(Company $company)
    {
        $message = '<strong>'.$company->name.'</strong>'.' was successfully deleted';
        $company->delete();
        return redirect()->route('co.company.index')->with('warning', $message);
    }

}

app/Http/Controllers/Supported/CustomerController.php
<?php

namespace App\Http\Controllers\Supported;

use App\Requester;
use App\Http\Controllers\Controller;
use App\Company;
use App\Ticket;

class CustomerController extends Controller
{
    public function index() {
        $customers = Requester::paginate(25);
        return view('supported.customer.index', compact('customers'));
    }

    public function create()
    {
        $companies = Company::pluck('name','id');
        return view('supported.customer.create', ['companies' => $companies]);
    }

    public function edit(Requester $customer)
    {
        $companies = Company::pluck('name','id');
        return view('supported.customer.edit', ['customer' => $customer, 'companies'=>$companies]);
    }

    public function update(Requester $customer)
    {
        $newAction = $this->validate(request(), [
            'name' => 'required|min:3',
            'address' => 'required|min:3',
            'email' => 'required|email',
            'phone' => 'required|min:5',
            'company_id' => 'required|integer'
        ]);

        $customer->update($newAction);

        return redirect()->route('cu.customer.index');
    }

    public function store()
    {
        $action = $this->validate(request(), [
            'name' => 'required|min:3',
            'address' => 'required|min:3',
            'email' => 'required|email',
            'phone' => 'required|min:5',
            'company_id' => 'required|integer'
        ]);

        Requester::create($action);

        return redirect()->route('cu.customer.index');
    }

    public function destroy(Requester $customer)
    {
        $message = '<strong>'.$customer->name.'</strong>'.' was successfully deleted';
        $tickets = Ticket::where('requester_id', $customer->id)->get()->count();
        if($tickets == 0) {
            $customer->delete();
        } else {
            $message = '<strong>'.$customer->name.'</strong>'.' currently has tickets and may not be deleted';
        }

        return redirect()->route('cu.customer.index')->with($tickets == 0 ? 'warning' : 'error', $message);
    }
}

app/Http/Controllers/Supported/SolutionController.php
<?php

namespace App\Http\Controllers\Supported;

use Illuminate\Http\Request;
use App\Solution;
use App\Http\Controllers\Controller;

class SolutionController extends Controller
{
    public function index() {
        $solutions = Solution::paginate(25);
        return view('supported.solution.index', compact('solutions'));
    }

    public function create()
    {
        return view('supported.solution.create');
    }

    public function edit(Solution $solution)
    {
        return view('supported.solution.edit', ['solution' => $solution]);
    }

    public function update(Solution $solution)
    {
        $newAction = $this->validate(request(), [
            'name' => 'required|min:3',
            'version' => 'required|min:3',
            'product_owner' => 'required|min:3'
        ]);

        $solution->update($newAction);

        return redirect()->route('so.solution.index');
    }

    public function store()
    {
        $action = $this->validate(request(), [
            'name' => 'required|min:3',
            'version' => 'required|min:3',
            'product_owner' => 'required|min:3'
        ]);

        $id = \Auth::user()->id;
        $action['user_id'] = $id;

        Solution::create($action);

        return redirect()->route('so.solution.index');
    }

    public function destroy(Solution $solution)
    {
        $message = '<strong>'.$solution->name.'</strong>'.' was successfully deleted';
        $solution->delete();
        return redirect()->route('so.solution.index')->with('warning', $message);
    }
}

app/Http/Controllers/Supported/SystemController.php
<?php

namespace App\Http\Controllers\Supported;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SystemController extends Controller
{
    public function index() {
        $systems = SupportedSystem::paginate(25);
        return view('supported.system.index', compact('systems'));
    }

    public function create()
    {
        return view('supported.system.create');
    }

    public function edit(SupportedSystem $system)
    {
        return view('supported.system.edit', ['system' => $system]);
    }

    public function update(SupportedSystem $system)
    {
        $newAction = $this->validate(request(), [
            'name' => 'required|min:3',
            'action_steps' => 'required|min:3',
            'client_script' => 'required|min:3'
        ]);

        $system->update($newAction);

        return redirect()->route('sys.system.index');
    }

    public function store()
    {
        $action = $this->validate(request(), [
            'name' => 'required|min:3',
            'action_steps' => 'required|min:3',
            'client_script' => 'required|min:3'
        ]);

        SupportedSystem::create($action);

        return redirect()->route('sys.system.index');
    }

    public function destroy(SupportedSystem $system)
    {
        $message = '<strong>'.$system->name.'</strong>'.' was successfully deleted';
        $system->delete();
        return redirect()->route('co.system.index')->with('warning', $message);
    }
}

resources/views/supported/company/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="description comment">
        <div class="breadcrumb">
            <a href="{{ route('co.company.index') }}"> Supported Companies</a>
        </div>
    </div>

    <h3>Create a supported company</h3>

    <div class="row">
        <div class="col-md-6">
            {{ Form::open(["url" => route("co.company.store")]) }}

            <div class="form-group">
                <label for="name">Company name:</label>
                <input class="form-control" type="text" name="name" value="{{ old('name') }}" placeholder="Company name"
                       required/>
            </div>

            <div class="form-group">
                <label for="address">Address:</label>
                <input class="form-control" type="text" name="address" value="{{ old('address') }}" placeholder="Address" required />
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label for="email">Email:</label>
                    <input class="form-control" type="email" name="email" value="{{ old('email') }}" placeholder="Email" required />
                </div>

                <div class="form-group col-md-6">
                    <label for="support_email">Support Email:</label>
                    <input class="form-control" type="email" name="support_email" value="{{ old('support_email') }}" placeholder="Support Email" required />
                </div>
            </div>

            <div class="form-group">
                <label for="web">Web:</label>
                <input class="form-control" type="url" name="web" value="{{ old('web') }}" placeholder="Web" required />
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label for="phone">Phone:</label>
                    <input class="form-control" type="tel" name="phone" value="{{ old('phone') }}" placeholder="Phone" required />
                </div>

                <div class="form-group col-md-6">
                    <label for="contact_number">Contact Number:</label>
                    <input class="form-control" type="text" name="contact_number" value="{{ old('contact_number') }}" placeholder="Contact Number" required/>
                </div>
            </div>

            {{--@include('components.mergeFields')--}}

            <button class="btn btn-primary" type="submit"> Save</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection
@section('styles')
    <link href="{{ asset('js/summernote/summernote.css') }}" rel="stylesheet">
@endsection
@section('scripts')
    @include('components.js.summernote')
@endsection

resources/views/supported/company/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="description comment">
        <div class="breadcrumb">
            <a href="{{ route('ac.actions.index') }}"> Supported Companies </a>
        </div>
    </div>

    <h3>#{{ $company->id }} {{ $company->name }}</h3>

    <div class="row">
        <div class="col-md-6">
            {{ Form::open(["url" => route('co.company.update', $company), 'method' => 'PUT']) }}

            <div class="form-group">
                <label for="name">Company name:</label>
                <input class="form-control" type="text" name="name" value="{{$company->name}}" placeholder="Company name" required/>
            </div>

            <div class="form-group">
                <label for="address">Address:</label>
                <input class="form-control" type="text" name="address" value="{{$company->address}}" placeholder="Address" required />
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label for="email">Email:</label>
                    <input class="form-control" type="email" name="email" value="{{$company->email}}" placeholder="Email" required />
                </div>

                <div class="form-group col-md-6">
                    <label for="support_email">Support Email:</label>
                    <input class="form-control" type="email" name="support_email" value="{{$company->support_email}}" placeholder="Support Email" required />
                </div>
            </div>

            <div class="form-group">
                <label for="web">Web:</label>
                <input class="form-control" type="url" name="web" value="{{$company->web}}" placeholder="Web" required />
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label for="phone">Phone:</label>
                    <input class="form-control" type="tel" name="phone" value="{{$company->phone}}" placeholder="Phone" required />
                </div>

                <div class="form-group col-md-6">
                    <label for="contact_number">Contact Number:</label>
                    <input class="form-control" type="text" name="contact_number" value="{{$company->contact_number}}" placeholder="Contact Number" required/>
                </div>
            </div>

            <a href="{{route('co.company.index')}}" class="btn btn-default"> Cancel</a>
            <button class="btn btn-primary" type="submit"> Update</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection
@section('styles')
    <link href="{{ asset('js/summernote/summernote.css') }}" rel="stylesheet">
@endsection
@section('scripts')
    @include('components.js.summernote')
@endsection

resources/views/supported/company/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-title">
        <h3>Supported Companies</h3>
    </div>

    <div class="row">
        <a class="btn btn-primary" href="{{ route("co.company.create") }}">@icon(plus) Company</a>
    </div>

    @paginator($companies)
    <table class="table table-hover table-striped table-condensed">
        <thead>
        <tr>
            <th> Name</th>
            <th> Contact Number</th>
            <th> Support Email</th>
            <th> Ticket Create Url</th>
            <th> Updated</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @forelse($companies as $company)
            <tr>
                <td> {{ $company->name}}</td>
                <td> {{ $company->contact_number}} </td>
                <td> {{ $company->support_email}}</td>
                <td> {{ route('requester.tickets.create', ['company' => $company->id]) }}</td>
                <td> {{ $company->updated_at->diffForHumans() }}</td>
                <td>
                    @can('update', $company)
                        {{--<a href="{{route('co.company.edit', $question)}}">@icon(pencil)</a>--}}
                    @endcan
                    <a class="btn btn-xs btn-default" href="{{ route('tickets.index', ['company' => $company->id]) }}">
                        @icon(inbox) Tickets
                    </a>
                    <a class="btn btn-xs btn-default" href="{{route('co.company.edit', $company)}}">@icon(pencil)</a>
                    @include('components.deleteButton', ['url' => 'co.company.destroy', 'model' => $company, 'btn_class' => 'btn-xs'])
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="6" class="empty-cell">No Companies Defined</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    @paginator($companies)
@endsection