routes/web.php
<?php

//Route::get('/', 'HomeController@index');

Route::redirect('/', 'login');

Auth::routes();

Route::get('auth/user/switch', 'UsersController@switchBack')->name('switch.back');

Route::group(['prefix' => 'requester'], function () {
    Route::get('tickets/view/{token}', 'Requester\RequesterTicketsController@show')->name('requester.tickets.show');
    Route::post('tickets/{token}/comments', 'Requester\RequesterCommentsController@store')->name('requester.comments.store');
    Route::get('tickets/{token}/rate', 'Requester\RequesterTicketsController@rate')->name('requester.tickets.rate');
    Route::get('tickets/create', 'Requester\RequesterTicketsController@create')->name('requester.tickets.create');
    Route::post('tickets/save', 'Requester\RequesterTicketsController@save')->name('requester.tickets.store');
});

Route::post('webhook/bitbucket', 'WebhookController@store');

Route::group(['middleware' => ['auth', 'userLocale']], function () {
    Route::get('actions/resolve/{ticket}', 'Actions\ActionsController@resolve')->name('ac.resolve');
    Route::post('actions/store', 'Actions\ActionsController@save')->name('ac.resolve.store');

    Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::post('password', 'ProfileController@password')->name('profile.password');
    Route::post('photo', 'ProfileController@photo')->name('profile.photo');

    Route::get('tickets/merge', 'Tickets\TicketsMergeController@index')->name('tickets.merge.index');
    //Route::post('tickets/merge', 'Tickets\TicketsMergeController@store')->name('tickets.merge.store');
    Route::get('tickets/search/{text}', 'Tickets\TicketsSearchController@index')->name('tickets.search');
    Route::resource('tickets', 'Tickets\TicketsController', ['except' => ['edit', 'destroy']]);
    Route::post('tickets/{ticket}/assign', 'Tickets\TicketsAssignController@store')->name('tickets.assign');
    Route::post('tickets/{ticket}/comments', 'CommentsController@store')->name('comments.store');
    Route::resource('tickets/{ticket}/tags', 'Tickets\TicketsTagsController', ['only' => ['store', 'destroy'], 'as' => 'tickets']);
    Route::post('tickets/{ticket}/reopen', 'Tickets\TicketsController@reopen')->name('tickets.reopen');

    Route::post('tickets/{ticket}/escalate', 'Tickets\TicketsEscalateController@store')->name('tickets.escalate.store');
    Route::delete('tickets/{ticket}/escalate', 'Tickets\TicketsEscalateController@destroy')->name('tickets.escalate.destroy');

    Route::post('tickets/{ticket}/issue', 'Tickets\TicketsIssueController@store')->name('tickets.issue.store');
    Route::post('tickets/{ticket}/idea', 'Tickets\TicketsIdeaController@store')->name('tickets.idea.store');

//    Route::resource('leads', 'Leads\LeadsController');
//    Route::get('leads/search/{text}', 'Leads\LeadsSearchController@index')->name('leads.search');
//    Route::post('leads/{lead}/assign', 'Leads\LeadAssignController@store')->name('leads.assign');
//    Route::post('leads/{lead}/status', 'Leads\LeadStatusController@store')->name('leads.status.store');
//    Route::resource('leads/{lead}/tags', 'Leads\LeadTagsController', ['only' => ['store', 'destroy'], 'as' => 'leads']);
//    Route::resource('leads/{lead}/tasks', 'Leads\LeadTasksController', ['only' => ['index', 'store', 'update', 'destroy'], 'as' => 'leads']);

    Route::resource('tasks', 'TasksController', ['only' => ['index', 'update', 'destroy']]);

    Route::resource('teams', 'TeamsController');
    Route::get('teams/{team}/agents', 'TeamAgentsController@index')->name('teams.agents');
    Route::get('teams/{token}/join', 'TeamMembershipController@index')->name('membership.index');
    Route::post('teams/{token}/join', 'TeamMembershipController@store')->name('membership.store');

    Route::get('dashboard', 'Reports\DashboardController@index')->name('dash.index');
    Route::get('slareport', 'Reports\SLAReportController@index')->name('sla.report');

    Route::group(['middleware' => 'can:see-admin'], function () {
        Route::resource('ideas', 'IdeasController');
        Route::get('roadmap', 'RoadmapController@index')->name('roadmap.index');
        Route::resource('ideas/{idea}/tags', 'IdeaTagsController', ['only' => ['store', 'destroy'], 'as' => 'ideas']);
        Route::post('ideas/{idea}/issue', 'IdeaIssueController@store')->name('ideas.issue.store');

        Route::resource('users', 'UsersController');
        Route::post('users/resend', 'UsersController@sendResetLinkEmail')->name('users.password.reset');
        Route::get('users/{user}/impersonate', 'UsersController@impersonate')->name('users.impersonate');
        Route::resource('settings', 'SettingsController', ['only' => ['edit', 'update']]);

        Route::resource('questions', 'Help\HelpQuestionsController', ['as' => 'qs']);
        Route::resource('help', 'Help\HelpAnswersController', ['as' => 'hp']);
        Route::resource('actions', 'MasterData\SupportedActionsController', ['as' => 'ac']);
        Route::resource('cause', 'MasterData\RootCauseController', ['as' => 'rc']);
        Route::resource('company', 'Supported\CompanyController', ['as' => 'co']);
        Route::resource('customer', 'Supported\CustomerController', ['as' => 'cu']);
        Route::resource('solution', 'Supported\SolutionController', ['as' => 'so']);
        Route::resource('sla', 'Reports\SLAController', ['only' => ['index', 'store', 'update']]);
    });

    Route::get('reports', 'ReportsController@index')->name('reports.index');

    Route::group(['prefix' => 'incidents'], function () {
        Route::get('all', 'IncidentsController@index')->name('incidents.index');
    });
});

resources/views/questions/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="description comment">
        <div class="breadcrumb">
            <a href="{{ route('qs.questions.index') }}"> Help configuration </a>
        </div>
    </div>

    <h3>Create help configuration question</h3>

    <div class="row">
        <div class="col-md-6">
            {{ Form::open(["url" => route("qs.questions.store")]) }}

            <div class="form-group">
                <label for="question">Question:</label>
                <input class="form-control" type="text" name="question" value="{{ old('question') }}" placeholder="Question" required />
            </div>

            <div class="form-group">
                <label for="route">Route to:</label>
                {{Form::select('route',$routes,old('route'),['class'=>'form-control'])}}
            </div>

            <div class="form-group">
                <label for="team">Team:</label>
                {{Form::select('team',$teams,old('team'),['class'=>'form-control'])}}
            </div>

            <div class="form-group">
                <label for="priority">Priority:</label>
                {{Form::select('priority',$priority,old('priority'),['class'=>'form-control'])}}
            </div>

            <button class="btn btn-primary" type="submit">@busy Save Configuration</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="description comment">
        <div class="breadcrumb">
            <a href="{{ route('qs.questions.index') }}"> Help configuration </a>
        </div>
    </div>

    <h3>#{{ $question->id }} {{ $question->question }}</h3>

    <div class="row">
        <div class="col-md-6">
            {{ Form::open(["url" => route('qs.questions.update', $question), 'method' => 'PUT']) }}

            <div class="form-group">
                <label for="question">Question:</label>
                <input class="form-control" type="text" name="question" value="{{$question->question}}" placeholder="Question" required />
            </div>

            <div class="form-group">
                <label for="route">Route to:</label>
                {{Form::select('route',$routes,$question->route,['class'=>'form-control'])}}
            </div>

            <div class="form-group">
                <label for="team">Team:</label>
                {{Form::select('team',$teams,$question->team,['class'=>'form-control'])}}
            </div>

            <div class="form-group">
                <label for="priority">Priority:</label>
                {{Form::select('priority',$priority,$question->priority,['class'=>'form-control'])}}
            </div>

            <button class="btn btn-primary" type="submit"> Save</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-title">
        <h3>Help Configuration</h3>
    </div>

    <div class="row">
        <a class="btn btn-primary" href="{{ route("qs.questions.create") }}">@icon(plus) Questions Routing</a>
    </div>

    @paginator($questions)
    <table class="table table-hover table-striped table-condensed">
        <thead>
        <tr>
            <th> Question</th>
            <th> Route</th>
            <th> Priority </th>
            <th> Team </th>
            <th> Created</th>
            <th> Updated </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($questions as $question)
            <tr>
                <td> {{ $question->question}}</td>
                <td> {{ $question->route}} </td>
                <td> {{ $question->priority }}</td>
                <td> {{ $question->hteam->name }}</td>
                <td> {{ $question->created_at->diffForHumans() }}</td>
                <td> {{ $question->updated_at->diffForHumans() }}</td>
                <td>
                    @can('update', $question)
                        {{--<a href="{{route('qs.questions.edit', $question)}}">@icon(pencil)</a>--}}
                    @endcan
                        <a href="{{route('qs.questions.edit', $question)}}">@icon(pencil)</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @paginator($questions)
@endsection