routes/web.php
<?php

//Route::get('/', 'HomeController@index');

Route::redirect('/', 'login');

Auth::routes();

Route::get('auth/user/switch', 'UsersController@switchBack')->name('switch.back');

Route::group(['prefix' => 'requester'], function () {
    Route::get('tickets/view/{token}', 'Requester\RequesterTicketsController@show')->name('requester.tickets.show');
    Route::post('tickets/{token}/comments', 'Requester\RequesterCommentsController@store')->name('requester.comments.store');
    Route::get('tickets/{token}/rate', 'Requester\RequesterTicketsController@rate')->name('requester.tickets.rate');
    Route::get('tickets/create', 'Requester\RequesterTicketsController@create')->name('requester.tickets.create');
    Route::post('tickets/save', 'Requester\RequesterTicketsController@save')->name('requester.tickets.store');
});

Route::post('webhook/bitbucket', 'WebhookController@store');

Route::group(['middleware' => ['auth', 'userLocale']], function () {
    Route::get('actions/resolve/{ticket}', 'Actions\ActionsController@resolve')->name('ac.resolve');
    Route::post('actions/store', 'Actions\ActionsController@save')->name('ac.resolve.store');

    Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::post('password', 'ProfileController@password')->name('profile.password');
    Route::post('photo', 'ProfileController@photo')->name('profile.photo');

    Route::get('tickets/merge', 'Tickets\TicketsMergeController@index')->name('tickets.merge.index');
    //Route::post('tickets/merge', 'Tickets\TicketsMergeController@store')->name('tickets.merge.store');
    Route::get('tickets/search/{text}', 'Tickets\TicketsSearchController@index')->name('tickets.search');
    Route::resource('tickets', 'Tickets\TicketsController', ['except' => ['edit', 'destroy']]);
    Route::post('tickets/{ticket}/assign', 'Tickets\TicketsAssignController@store')->name('tickets.assign');
    Route::post('tickets/{ticket}/comments', 'CommentsController@store')->name('comments.store');
    Route::resource('tickets/{ticket}/tags', 'Tickets\TicketsTagsController', ['only' => ['store', 'destroy'], 'as' => 'tickets']);
    Route::post('tickets/{ticket}/reopen', 'Tickets\TicketsController@reopen')->name('tickets.reopen');

    Route::post('tickets/{ticket}/escalate', 'Tickets\TicketsEscalateController@store')->name('tickets.escalate.store');
    Route::delete('tickets/{ticket}/escalate', 'Tickets\TicketsEscalateController@destroy')->name('tickets.escalate.destroy');

    Route::post('tickets/{ticket}/issue', 'Tickets\TicketsIssueController@store')->name('tickets.issue.store');
    Route::post('tickets/{ticket}/idea', 'Tickets\TicketsIdeaController@store')->name('tickets.idea.store');

//    Route::resource('leads', 'Leads\LeadsController');
//    Route::get('leads/search/{text}', 'Leads\LeadsSearchController@index')->name('leads.search');
//    Route::post('leads/{lead}/assign', 'Leads\LeadAssignController@store')->name('leads.assign');
//    Route::post('leads/{lead}/status', 'Leads\LeadStatusController@store')->name('leads.status.store');
//    Route::resource('leads/{lead}/tags', 'Leads\LeadTagsController', ['only' => ['store', 'destroy'], 'as' => 'leads']);
//    Route::resource('leads/{lead}/tasks', 'Leads\LeadTasksController', ['only' => ['index', 'store', 'update', 'destroy'], 'as' => 'leads']);

    Route::resource('tasks', 'TasksController', ['only' => ['index', 'update', 'destroy']]);

    Route::resource('teams', 'TeamsController');
    Route::get('teams/{team}/agents', 'TeamAgentsController@index')->name('teams.agents');
    Route::get('teams/{token}/join', 'TeamMembershipController@index')->name('membership.index');
    Route::post('teams/{token}/join', 'TeamMembershipController@store')->name('membership.store');

    Route::get('dashboard', 'Reports\DashboardController@index')->name('dash.index');
    Route::get('slareport', 'Reports\SLAReportController@index')->name('sla.report');

    Route::group(['middleware' => 'can:see-admin'], function () {
        Route::resource('ideas', 'IdeasController');
        Route::get('roadmap', 'RoadmapController@index')->name('roadmap.index');
        Route::resource('ideas/{idea}/tags', 'IdeaTagsController', ['only' => ['store', 'destroy'], 'as' => 'ideas']);
        Route::post('ideas/{idea}/issue', 'IdeaIssueController@store')->name('ideas.issue.store');

        Route::resource('users', 'UsersController');
        Route::post('users/resend', 'UsersController@sendResetLinkEmail')->name('users.password.reset');
        Route::get('users/{user}/impersonate', 'UsersController@impersonate')->name('users.impersonate');
        Route::resource('settings', 'SettingsController', ['only' => ['edit', 'update']]);

        Route::resource('questions', 'Help\HelpQuestionsController', ['as' => 'qs']);
        Route::resource('help', 'Help\HelpAnswersController', ['as' => 'hp']);
        Route::resource('actions', 'MasterData\SupportedActionsController', ['as' => 'ac']);
        Route::resource('cause', 'MasterData\RootCauseController', ['as' => 'rc']);
        Route::resource('company', 'Supported\CompanyController', ['as' => 'co']);
        Route::resource('customer', 'Supported\CustomerController', ['as' => 'cu']);
        Route::resource('solution', 'Supported\SolutionController', ['as' => 'so']);
        Route::resource('sla', 'Reports\SLAController', ['only' => ['index', 'store', 'update']]);
    });

    Route::get('reports', 'ReportsController@index')->name('reports.index');

    Route::group(['prefix' => 'incidents'], function () {
        Route::get('all', 'IncidentsController@index')->name('incidents.index');
    });
});

app/RootCause.php
<?php

namespace App;

class RootCause extends BaseModel
{
    protected $table = 'root_causes';
}

app/Http/Controllers/MasterData/RootCauseController.php
<?php

namespace App\Http\Controllers\MasterData;

use Illuminate\Http\Request;
use App\RootCause;
use App\Http\Controllers\Controller;

class RootCauseController extends Controller
{
    public function index()
    {
        $rootcauses = RootCause::paginate(25);
        return view('rootcause.index', compact('rootcauses'));
    }

    public function create()
    {
        return view('rootcause.create');
    }

    public function edit(RootCause $cause)
    {
        return view('rootcause.edit', ['rootcause' => $cause]);
    }

    public function update(RootCause $cause)
    {
        $newRootCause = $this->validate(request(), [
            'name' => 'required|min:3',
            'description' => 'required|min:3'
        ]);

        $cause->update($newRootCause);

        return redirect()->route('rc.cause.index');
    }

    public function store()
    {
        $rootcause = $this->validate(request(), [
            'name' => 'required|min:3',
            'description' => 'required|min:3'
        ]);

        RootCause::create($rootcause);

        return redirect()->route('rc.cause.index');
    }

    public function destroy(RootCause $cause)
    {
        $message = '<strong>'.$cause->name.'</strong>'.' was successfully deleted';
        $cause->delete();
        return redirect()->route('rc.cause.index')->with('success', $message);
    }
}

resources/views/rootcause/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="description comment">
        <div class="breadcrumb">
            <a href="{{ route('rc.cause.index') }}"> Root Cause </a>
        </div>
    </div>

    <h3>Create root cause</h3>

    <div class="row">
        <div class="col-md-6">
            {{ Form::open(["url" => route("rc.cause.store")]) }}

            <div class="form-group">
                <label for="name">Description:</label>
                <input class="form-control" type="text" name="name" value="{{ old('name') }}" placeholder="Name"
                       required/>
            </div>

            <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control" name="description" placeholder="Description" rows="3" required>
                    {{ old('description') }}
                </textarea>
            </div>

            {{--@include('components.mergeFields')--}}

            <button class="btn btn-primary" type="submit"> Save</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/rootcause/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="description comment">
        <div class="breadcrumb">
            <a href="{{ route('rc.cause.index') }}"> Root cause </a>
        </div>
    </div>

    <h3>#{{ $rootcause->id }} {{ $rootcause->name }}</h3>

    <div class="row">
        <div class="col-md-6">
            {{ Form::open(["url" => route('rc.cause.update', $rootcause), 'method' => 'PUT']) }}

            <div class="form-group">
                <label for="name">Description:</label>
                <input class="form-control" type="text" name="name" value="{{$rootcause->name}}" placeholder="Description" required/>
            </div>

            <div class="form-group">
                <label for="description">Action Steps:</label>
                <textarea class="form-control" name="description" placeholder="Description" rows="3" required>
                    {{$rootcause->description}}
                </textarea>
            </div>

            <a href="{{route('rc.cause.index')}}" class="btn btn-default"> Cancel</a>
            <button class="btn btn-primary" type="submit"> Update</button>
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/rootcause/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="page-title">
        <h3>Root Cause</h3>
    </div>

    <div class="row">
        <a class="btn btn-primary" href="{{ route("rc.cause.create") }}">@icon(plus) Root cause</a>
    </div>

    @paginator($rootcauses)
    <table class="table table-hover table-striped table-condensed">
        <thead>
        <tr>
            <th> Name</th>
            <th> Description</th>
            <th> Updated </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @forelse($rootcauses as $rootcause)
            <tr>
                <td> {{ $rootcause->name}}</td>
                <td> {{ str_limit($rootcause->description, 50, '...')}} </td>
                <td> {{ $rootcause->updated_at->diffForHumans() }}</td>
                <td>
                    @can('update', $rootcause)
                        {{--<a class="btn btn-xs btn-default" href="{{route('rc.cause.edit', $rootcause)}}">@icon(pencil)</a>--}}
                    @endcan
                        <a class="btn btn-xs btn-default" href="{{route('rc.cause.edit', $rootcause)}}">@icon(pencil)</a>
                        @include('components.deleteButton', ['url' => 'rc.cause.destroy', 'model' => $rootcause, 'btn_class' => 'btn-xs'])
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="6" class="empty-cell">No root causes defined</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    @paginator($rootcauses)
@endsection